name: JSON check
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@6e25e4304c75d72195ad8c6fca739cb2e99c3fb1 # v2.0.3
        with:
          pattern: "\\.json"
